INSERT INTO emojis (symbol, description) VALUES
('https://twemoji.maxcdn.com/v/latest/72x72/1f600.png', 'Grinning Face'),
('https://twemoji.maxcdn.com/v/latest/72x72/1f601.png', 'Beaming Face'),
('https://twemoji.maxcdn.com/v/latest/72x72/1f602.png', 'Face with Tears of Joy'),
('https://twemoji.maxcdn.com/v/latest/72x72/1f603.png', 'Grinning Face with Big Eyes'),
('https://twemoji.maxcdn.com/v/latest/72x72/1f604.png', 'Grinning Face with Smiling Eyes'),
('https://twemoji.maxcdn.com/v/latest/72x72/1f605.png', 'Grinning Face with Sweat'),
('https://twemoji.maxcdn.com/v/latest/72x72/1f606.png', 'Laughing'),
('https://twemoji.maxcdn.com/v/latest/72x72/1f607.png', 'Smiling Face with Halo'),
('https://twemoji.maxcdn.com/v/latest/72x72/1f608.png', 'Smiling Face with Horns'),
('https://twemoji.maxcdn.com/v/latest/72x72/1f609.png', 'Winking Face'),
('https://twemoji.maxcdn.com/v/latest/72x72/1f60a.png', 'Smiling Face'),
('https://twemoji.maxcdn.com/v/latest/72x72/1f60b.png', 'Face Savoring Food'),
('https://twemoji.maxcdn.com/v/latest/72x72/1f60c.png', 'Relieved Face'),
('https://twemoji.maxcdn.com/v/latest/72x72/1f60d.png', 'Heart Eyes'),
('https://twemoji.maxcdn.com/v/latest/72x72/1f60e.png', 'Smiling Face with Sunglasses'),
('https://twemoji.maxcdn.com/v/latest/72x72/1f60f.png', 'Smirking Face'),
('https://twemoji.maxcdn.com/v/latest/72x72/1f610.png', 'Neutral Face'),
('https://twemoji.maxcdn.com/v/latest/72x72/1f611.png', 'Expressionless Face'),
('https://twemoji.maxcdn.com/v/latest/72x72/1f612.png', 'Unamused Face'),
('https://twemoji.maxcdn.com/v/latest/72x72/1f613.png', 'Downcast Face with Sweat'),
('https://twemoji.maxcdn.com/v/latest/72x72/1f614.png', 'Pensive Face'),
('https://twemoji.maxcdn.com/v/latest/72x72/1f615.png', 'Confused Face'),
('https://twemoji.maxcdn.com/v/latest/72x72/1f616.png', 'Confounded Face'),
('https://twemoji.maxcdn.com/v/latest/72x72/1f617.png', 'Kissing Face'),
('https://twemoji.maxcdn.com/v/latest/72x72/1f618.png', 'Face Blowing a Kiss'),
('https://twemoji.maxcdn.com/v/latest/72x72/1f619.png', 'Kissing Face with Smiling Eyes'),
('https://twemoji.maxcdn.com/v/latest/72x72/1f61a.png', 'Kissing Face with Closed Eyes'),
('https://twemoji.maxcdn.com/v/latest/72x72/1f61b.png', 'Face with Tongue'),
('https://twemoji.maxcdn.com/v/latest/72x72/1f61c.png', 'Winking Face with Tongue'),
('https://twemoji.maxcdn.com/v/latest/72x72/1f61d.png', 'Squinting Face with Tongue');
